0.2.0, + install faster, * upgrade electron version in shell

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -14,7 +14,7 @@ h_dir() {
 }
 
 h_ver() {
-  echo "1.4.9"
+  echo "5.0.6"
 }
 
 h_get_os() {
@@ -28,42 +28,63 @@ h_get_os() {
   echo $H_OS
 }
 
-h_download() {
-  curl --fail -s -I $1 >/dev/null
-  curl --progress-bar -L -o $2 $1 >/dev/null
-}
-
 h_source() {
   # 1 for ver, 2 for os
   echo "https://npm.taobao.org/mirrors/electron/$1/electron-v$1-$2-x64.zip"
 }
 
+h_download() {
+  curl --fail -s -I $1 >/dev/null
+  curl --progress-bar -L -o $2 $1 >/dev/null
+}
+
 h_install_electron() {
+  h_has unzip || { echo "unzip not installed"; exit 1; }
   echo "> install electron"
   local ELECTRON_SOURCE=$(h_source $(h_ver) $(h_get_os uname))
   local ELECTRON_TARGET_DIR=$(h_dir)/electron/$(h_ver)
   local ELECTRON_TARGET="$ELECTRON_TARGET_DIR/electron.zip"
-  echo $ELECTRON_TARGET_DIR
-  echo $ELECTRON_SOURCE
-  mkdir -p $ELECTRON_TARGET_DIR
-  h_download $ELECTRON_SOURCE $ELECTRON_TARGET || {
-    echo >&2 "failed to download electron"
-    return 1
-  }
-  unzip -n $ELECTRON_TARGET -d $ELECTRON_TARGET_DIR >/dev/null
-  rm -f $ELECTRON_TARGET
+  if [ ! -d $ELECTRON_TARGET_DIR ]; then
+    echo $ELECTRON_TARGET_DIR
+    echo $ELECTRON_SOURCE
+    mkdir -p $ELECTRON_TARGET_DIR
+    h_download $ELECTRON_SOURCE $ELECTRON_TARGET || {
+      echo >&2 "failed to download electron"
+      return 1
+    }
+    unzip -n $ELECTRON_TARGET -d $ELECTRON_TARGET_DIR >/dev/null
+    rm -f $ELECTRON_TARGET
+  fi
 }
 
 h_install_hydrion() {
   echo "> install hydrion"
+  if [ -z $HYDRION_ENV ]; then
+    HYDRION_ENV="prod"
+  fi
+
+  # try to enter test mode
+  if [ $HYDRION_ENV == "test" ]; then
+    sudo rm -rf /usr/local/bin/hydrion
+    sudo ln -s $(pwd)/bin/startup /usr/local/bin/hydrion
+    exit 0;
+  fi
+
+  # update source
   local HYDRION_SOURCE_DIR=$(h_dir)/source
-  rm -rf $HYDRION_SOURCE_DIR
-  mkdir -p $HYDRION_SOURCE_DIR
-  git clone https://github.com/sartrey/hydrion.git $HYDRION_SOURCE_DIR
-  ln -s $HYDRION_SOURCE_DIR/bin/startup /usr/local/bin/hydrion
+  if [ -d $HYDRION_SOURCE_DIR ]; then
+    cd $HYDRION_SOURCE_DIR
+    git pull
+    cd -
+  else
+    mkdir -p $HYDRION_SOURCE_DIR
+    git clone https://github.com/sartrey/hydrion.git $HYDRION_SOURCE_DIR
+  fi
+  # create command link
+  sudo rm -rf /usr/local/bin/hydrion
+  sudo ln -s $HYDRION_SOURCE_DIR/bin/startup /usr/local/bin/hydrion
 }
 
 h_install_electron
-h_install_hydrion
-
+h_install_hydrion  
 }
